<?php

return [
    'roles' => [
        "super_admin"   =>  "super_admin",
        "admin"         =>  "admin",
        "manager"       =>  "manager",
        "team"          =>  "team",
        "client"        =>  "client",
    ],
    'functionalities' => [
        'dashboard' => [
            'tag'   => 'DASH',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => null,
            'order' => 0,
            'data'  => [
                'route' => 'home',
                'icon'  => 'menu',
            ],
        ],
        'user' => [
            'tag'   => 'USER',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => null,
            'order' => 1,
            'data'  => [
                'route' => 'user-index',
                'icon'  => 'menu',
            ],
        ],
        'user-index' => [
            'tag'   => 'USERIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 0,
            'data'  => [],
        ],
        'user-create' => [
            'tag'   => 'USERCRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 1,
            'data'  => [],
        ],
        'user-update' => [
            'tag'   => 'USERUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 2,
            'data'  => [],
        ],
        'user-delete' => [
            'tag'   => 'USERDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 3,
            'data'  => [],
        ],
        'show-team-lead' => [
            'tag'   => 'USERSHOWTMLEAD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 4,
            'data'  => [],
        ],
        'assign-team-lead' => [
            'tag'   => 'USERASTMLEAD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 5,
            'data'  => [],
        ],
        'role' => [
            'tag'   => 'ROLE',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => null,
            'order' => 2,
            'data'  => [
                'route' => 'role-index',
                'icon'  => 'menu',
            ],
        ],
        'role-index' => [
            'tag'   => 'ROLEIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 0,
            'data'  => [],
        ],
        'role-create' => [
            'tag'   => 'ROLECRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 1,
            'data'  => [],
        ],
        'role-update' => [
            'tag'   => 'ROLEUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 2,
            'data'  => [],
        ],
        'role-delete' => [
            'tag'   => 'ROLEDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 3,
            'data'  => [],
        ],
        'role-permission' => [
            'tag'   => 'ROLEPRMSION',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => null,
            'order' => 4,
            'data'  => [],
        ],
    ],
];
