<?php

return [
    'roles' => [
        "super_admin"   =>  "super_admin",
        "admin"         =>  "admin",
        "manager"       =>  "manager",
        "team"          =>  "team",
        "client"        =>  "client",
    ],
    'functionalities' => [
        'dashboard' => [
            'tag'   => 'DASH',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => null,
            'order' => 0,
            'data'  => [
                'route' => 'home',
                'icon'  => 'fas fa-tachometer-alt', // dashboard
            ],
        ],
        'management' => [
            'tag' => 'MGMT',
            'target'=> 'menu',
            'parent_id' => null,
            'status'=> 1,
            'order' => 2,
            'data' => ['icon' => 'fas fa-cogs'], // management/settings
        ],
        'user' => [
            'tag'   => 'USER',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'management_id',
            'order' => 1,
            'data'  => [
                'route' => 'user-index',
                'icon'  => 'fas fa-users', // users
            ],
        ],
        'user-index' => [
            'tag'   => 'USERIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'user_id',
            'order' => 0,
            'data'  => [],
        ],
        'user-create' => [
            'tag'   => 'USERCRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'user_id',
            'order' => 1,
            'data'  => [],
        ],
        'user-update' => [
            'tag'   => 'USERUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'user_id',
            'order' => 2,
            'data'  => [],
        ],
        'user-delete' => [
            'tag'   => 'USERDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'user_id',
            'order' => 3,
            'data'  => [],
        ],
        'show-team-lead' => [
            'tag'   => 'USERSHOWTMLEAD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'user_id',
            'order' => 4,
            'data'  => [],
        ],
        'assign-team-lead' => [
            'tag'   => 'USERASTMLEAD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'user_id',
            'order' => 5,
            'data'  => [],
        ],
        'client' => [
            'tag'   => 'CLIENT',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'management_id',
            'order' => 2,
            'data'  => [
                'route' => 'client-index',
                'icon'  => 'fas fa-user-tie', // clients
            ],
        ],
        'client-index' => [
            'tag'   => 'CLIENTIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'client_id',
            'order' => 0,
            'data'  => [],
        ],
        'client-create' => [
            'tag'   => 'CLIENTCRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'client_id',
            'order' => 1,
            'data'  => [],
        ],
        'client-update' => [
            'tag'   => 'CLIENTUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'client_id',
            'order' => 2,
            'data'  => [],
        ],
        'client-delete' => [
            'tag'   => 'CLIENTDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'client_id',
            'order' => 3,
            'data'  => [],
        ],
        'role' => [
            'tag'   => 'ROLE',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'management_id',
            'order' => 3,
            'data'  => [
                'route' => 'role-index',
                'icon'  => 'fas fa-user-shield', // roles/permissions
            ],
        ],
        'role-index' => [
            'tag'   => 'ROLEIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'role_id',
            'order' => 0,
            'data'  => [],
        ],
        'role-create' => [
            'tag'   => 'ROLECRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'role_id',
            'order' => 1,
            'data'  => [],
        ],
        'role-update' => [
            'tag'   => 'ROLEUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'role_id',
            'order' => 2,
            'data'  => [],
        ],
        'role-delete' => [
            'tag'   => 'ROLEDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'role_id',
            'order' => 3,
            'data'  => [],
        ],
        'role-permission' => [
            'tag'   => 'ROLEPRMSION',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'role_id',
            'order' => 4,
            'data'  => [],
        ],
        'operations' => [
            'tag' => 'OPR',
            'target'=> 'menu',
            'parent_id' => null,
            'status'=> 1,
            'order' => 3,
            'data' => ['icon' => 'fas fa-briefcase'], // operations/work]
        ],
        'project' => [
            'tag'   => 'PROJECT',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'operations_id',
            'order' => 1,
            'data'  => [
                'route' => 'project-index',
                'icon'  => 'fas fa-project-diagram', // project
            ],
        ],
        'project-index' => [
            'tag'   => 'PROJECTIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_id',
            'order' => 0,
            'data'  => [],
        ],
        'project-create' => [
            'tag'   => 'PROJECTCRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_id',
            'order' => 1,
            'data'  => [],
        ],
        'project-update' => [
            'tag'   => 'PROJECTUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_id',
            'order' => 2,
            'data'  => [],
        ],
        'project-delete' => [
            'tag'   => 'PROJECTDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_id',
            'order' => 3,
            'data'  => [],
        ],
        'project-view' => [
            'tag'   => 'PROJECTVIEW',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_id',
            'order' => 3,
            'data'  => [],
        ],
        'project_role' => [
            'tag'   => 'PROJECTROLE',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'operations_id',
            'order' => 2,
            'data'  => [
                'route' => 'project-role-index',
                'icon'  => 'fas fa-user-cog', // project roles
            ],
        ],
        'project-role-index' => [
            'tag'   => 'PROJECTROLEIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_role_id',
            'order' => 0,
            'data'  => [],
        ],
        'project-role-create' => [
            'tag'   => 'PROJECTROLECRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_role_id',
            'order' => 1,
            'data'  => [],
        ],
        'project-role-update' => [
            'tag'   => 'PROJECTROLEUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_role_id',
            'order' => 2,
            'data'  => [],
        ],
        'project-role-delete' => [
            'tag'   => 'PROJECTROLEDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'project_role_id',
            'order' => 3,
            'data'  => [],
        ],
        'task' => [
            'tag'   => 'TASK',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'operations_id',
            'order' => 3,
            'data'  => [
                'route' => 'task-index',
                'icon'  => 'fas fa-tasks', // tasks
            ],
        ],
        'task-index' => [
            'tag'   => 'TASKIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'task_id',
            'order' => 0,
            'data'  => [],
        ],
        'task-create' => [
            'tag'   => 'TASKCRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'task_id',
            'order' => 1,
            'data'  => [],
        ],
        'task-update' => [
            'tag'   => 'TASKUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'task_id',
            'order' => 2,
            'data'  => [],
        ],
        'task-delete' => [
            'tag'   => 'TASKDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'task_id',
            'order' => 3,
            'data'  => [],
        ],
        'task-view' => [
            'tag'   => 'TASKVIEW',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'task_id',
            'order' => 4,
            'data'  => [],
        ],
        'finance' => [
            'tag' => 'FINS',
            'target'=> 'menu',
            'parent_id' => null,
            'status'=> 1,
            'order' => 4,
            'data' => ['icon' => 'fas fa-wallet'], // finance]
        ],
        'invoice' => [
            'tag'   => 'INVOICE',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'finance_id',
            'order' => 1,
            'data'  => [
                'route' => 'invoice-index',
                'icon'  => 'fas fa-file-invoice-dollar', // invoice
            ],
        ],
        'invoice-index' => [
            'tag'   => 'INVOICEIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'invoice_id',
            'order' => 0,
            'data'  => [],
        ],
        'invoice-create' => [
            'tag'   => 'INVOICECRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'invoice_id',
            'order' => 1,
            'data'  => [],
        ],
        'invoice-update' => [
            'tag'   => 'INVOICEUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'invoice_id',
            'order' => 2,
            'data'  => [],
        ],
        'invoice-delete' => [
            'tag'   => 'INVOICEDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'invoice_id',
            'order' => 3,
            'data'  => [],
        ],
        'invoice-view' => [
            'tag'   => 'INVOICEVIEW',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'invoice_id',
            'order' => 4,
            'data'  => [],
        ],
        'payment' => [
            'tag'   => 'PAYMENT',
            'target'=> 'menu',
            'status'=> 1,
            'parent_id' => 'finance_id',
            'order' => 1,
            'data'  => [
                'route' => 'payment-index',
                'icon'  => 'fas fa-file-payment-dollar', // payment
            ],
        ],
        'payment-index' => [
            'tag'   => 'PAYMENTIND',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'payment_id',
            'order' => 0,
            'data'  => [],
        ],
        'payment-create' => [
            'tag'   => 'PAYMENTCRT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'payment_id',
            'order' => 1,
            'data'  => [],
        ],
        'payment-update' => [
            'tag'   => 'PAYMENTUPD',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'payment_id',
            'order' => 2,
            'data'  => [],
        ],
        'payment-delete' => [
            'tag'   => 'PAYMENTDLT',
            'target'=> 'action',
            'status'=> 1,
            'parent_id' => 'payment_id',
            'order' => 3,
            'data'  => [],
        ],
    ],
];
